# Introduction to NumPy and PyTorch

Numpy is a widely used Python library for scientific computing with
multidimensional arrays.

PyTorch is an increasingly popular library used for Deep Learning research and applications. It is similar to numpy in that it is built around the manipulation of multidimensional arrays, but with a few additional features:
* GPU support
* Automatic differentiation
* Other utilities to facilitate building and training neural network

This notebook will cover some of the essential features of NumPy and PyTorch. Examples from each framework will be presented side-by-side to highlight the similarities (and occasional differences) between their APIs.

In particular, we will first explore some of the core operations involving the central data structures in each library, the NumPy `ndarray` and the PyTorch `Tensor`.

Finally, we will look at the basics of automatic differentiation in PyTorch.

The official documentation is a good place to learn more:
* https://docs.scipy.org/doc/numpy/user/index.html
* https://pytorch.org/docs/stable/index.html
* https://pytorch.org/tutorials/

In [1]:
import numpy as np
import torch

np.random.seed(0)
print(np.random.rand(4))
np.random.seed(0)
print(np.random.rand(4))

torch.manual_seed(1)
print(torch.rand(2))
torch.manual_seed(1)
print(torch.rand(2))

[0.5488135  0.71518937 0.60276338 0.54488318]
[0.5488135  0.71518937 0.60276338 0.54488318]
tensor([0.7576, 0.2793])
tensor([0.7576, 0.2793])


### Creating arrays

##### From list

In [2]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [3]:
a_ = torch.Tensor([1, 2, 3])
a_

tensor([1., 2., 3.])

In [4]:
a_long = torch.LongTensor([1, 2, 3])
a_long

tensor([1, 2, 3])

#### Empty array

In [5]:
b = np.empty((3, 2))
b

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [6]:
b_ = torch.empty((3, 2))
b_

tensor([[ 0.0000e+00, -3.6893e+19],
        [ 1.6433e+25,  1.0845e-19],
        [-6.1796e-26,  4.5814e-41]])

#### Zeroes

In [7]:
c = np.zeros((2, 3))
c

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
c_ = torch.zeros((2, 3))
c_

tensor([[0., 0., 0.],
        [0., 0., 0.]])

#### Ones

In [9]:
d = np.ones(3)
d

array([1., 1., 1.])

In [10]:
d_ = torch.ones(3)
d_

d_ = torch.ones((3,3))
d_ 

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

#### Samples from Uniform[0,1]

In [11]:
e = np.random.random((2, 3))
e

array([[0.4236548 , 0.64589411, 0.43758721],
       [0.891773  , 0.96366276, 0.38344152]])

In [12]:
e_ = torch.rand((2, 3))
e_

tensor([[0.4031, 0.7347, 0.0293],
        [0.7999, 0.3971, 0.7544]])

### Basic properties

#### Shape

In [13]:
print(b)
b.shape

[[0. 0.]
 [0. 0.]
 [0. 0.]]


(3, 2)

In [14]:
print(b_)
b_.shape

tensor([[ 0.0000e+00, -3.6893e+19],
        [ 1.6433e+25,  1.0845e-19],
        [-6.1796e-26,  4.5814e-41]])


torch.Size([3, 2])

#### dtype

In [15]:
print(a.dtype)
print(e.dtype)

int64
float64


In [16]:
print(a_long.dtype)
print(e_.dtype)

torch.int64
torch.float32


### Indexing

#### Integer indexing

In [17]:
print(b)
print(b[0])
print(b[0, 0])

[[0. 0.]
 [0. 0.]
 [0. 0.]]
[0. 0.]
0.0


In [18]:
print(b_)
print(b_[0])
print(b_[1])
print(b_[0, 0])

tensor([[ 0.0000e+00, -3.6893e+19],
        [ 1.6433e+25,  1.0845e-19],
        [-6.1796e-26,  4.5814e-41]])
tensor([ 0.0000e+00, -3.6893e+19])
tensor([1.6433e+25, 1.0845e-19])
tensor(0.)


#### Slicing

In [19]:
print(b)
print()

print(b[:2])
print()

print(b[2:])
print()

print(b[1:3])
print()

print(b[:, :1])
print()

print(b[:2, :2])

[[0. 0.]
 [0. 0.]
 [0. 0.]]

[[0. 0.]
 [0. 0.]]

[[0. 0.]]

[[0. 0.]
 [0. 0.]]

[[0.]
 [0.]
 [0.]]

[[0. 0.]
 [0. 0.]]


In [20]:
print(b_[:2])
print(b_[1:3])
print(b_[:, :1])
print(b_[:2, :2])

tensor([[ 0.0000e+00, -3.6893e+19],
        [ 1.6433e+25,  1.0845e-19]])
tensor([[ 1.6433e+25,  1.0845e-19],
        [-6.1796e-26,  4.5814e-41]])
tensor([[ 0.0000e+00],
        [ 1.6433e+25],
        [-6.1796e-26]])
tensor([[ 0.0000e+00, -3.6893e+19],
        [ 1.6433e+25,  1.0845e-19]])


#### Boolean indexing

In [21]:
print(a)
print()
idx = a >= 2
print(idx)
print(a[idx])

[1 2 3]

[False  True  True]
[2 3]


In [22]:
idx_ = a_ >= 2
print(idx_)
print(a_[idx_])

tensor([0, 1, 1], dtype=torch.uint8)
tensor([2., 3.])


### Mathematical operations

#### Sum

In [31]:
print(e)
print()
print(e.sum())
print(np.sum(e))
print(e.sum(axis=0))

[[0.4236548  0.64589411 0.43758721]
 [0.891773   0.96366276 0.38344152]]

3.7460134037771406
3.7460134037771406
[1.3154278  1.60955687 0.82102873]


In [24]:
print(e_)
print()
print(e_.sum())
print(torch.sum(e_))
print(e_.sum(dim=0))
print(e_.shape)

tensor([[0.4031, 0.7347, 0.0293],
        [0.7999, 0.3971, 0.7544]])

tensor(3.1184)
tensor(3.1184)
tensor([1.2029, 1.1318, 0.7837])
torch.Size([2, 3])


#### Elementwise sum

In [25]:
print(a)
print(d)
print()
print(a + d)

[1 2 3]
[1. 1. 1.]

[2. 3. 4.]


In [26]:
print(a_)
print(d_)
print()
print(a_ + d_)

tensor([1., 2., 3.])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

tensor([[2., 3., 4.],
        [2., 3., 4.],
        [2., 3., 4.]])


#### Elementwise multiplication

In [27]:
print(a)
print(d)
print()
print(a * d)

[1 2 3]
[1. 1. 1.]

[1. 2. 3.]


In [28]:
print(a_)
print(d_)
print()
print(a_ * d_)

tensor([1., 2., 3.])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

tensor([[1., 2., 3.],
        [1., 2., 3.],
        [1., 2., 3.]])


#### Dot product

In [29]:
print(a)
print(d)
print()
print(np.dot(a, d))
print(a.dot(d))

[1 2 3]
[1. 1. 1.]

6.0
6.0


In [30]:
print(a_)
print(d_)
print()
print(torch.dot(a_, d_))
print(a_.dot(d_))

tensor([1., 2., 3.])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])



RuntimeError: dot: Expected 1-D argument tensor, but got 2-D

#### Matrix multiplication

In [ ]:
print(a)
print(b)
print()
print(np.matmul(a, b))

In [ ]:
print(a_)
print(b_)
print()
print(torch.matmul(a_, b_))
print(a_ @ b_)

### Broadcasting

#### Compatible shapes

In [ ]:
f = torch.rand((2, 1, 3))
g = torch.ones((3, 3))
print(f)
print(g)

In [ ]:
print(f)
print(g)
print()
print(f + g)
print(f * g)

print((f + g).shape)
print((f * g).shape)

In [ ]:
# print((1 + g).shape)
# print((4 * g).shape)
# print((f + g).shape)
# print((f * g).shape)

print(f.shape)
print(g.shape)
f @ g
# (f @ g).shape

#### Incompatible shapes

In [ ]:
h = np.random.random((2, 3))
i = np.random.random((2, 2))
print(h.shape)
print(i.shape)

# Raises error
h + i

### Converting between NumPy and PyTorch

In [ ]:
arr_np = np.random.random((5, 5))
arr_th = torch.rand((5, 5))

# From numpy
torch.Tensor(arr_np)
print(torch.from_numpy(arr_np))

# To numpy
print()
print(arr_th.numpy())


### Autograd basics

In [ ]:
W = torch.randn((7, 5), requires_grad=True)
x = torch.randn(5)
x = torch.matmul(W, x)
z = x.sum()
print(W)
print(z)

In [ ]:
z.backward()

In [ ]:
W.grad

In [ ]:
# Another example involving differentiating through a for-loop
W = torch.randn((5, 5), requires_grad=True)
x = torch.randn(5)
for i in range(3):
    x = torch.matmul(W, x)
z = x.sum()
z.backward()
print(W.grad)